# Generated by Django 3.2.13 on 2022-08-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=150)),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
    ]
